# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49087eec66df2fc3d94060ede672bacacdb0b7fc8b9b1e3ac780b60123f1eb36c416dea8a43cab6b9848792f59d3031d02f8f4d4e73967a6f1075eb7765e7222

test:
  secret_key_base: 7d4c8f8f27d806c711da047cf0cc7ccb5bfed1ff9e183de54846811cebbeca35d793808f5874b3efe853bf11480820adb63998c5ebe5aa93ecf8ce17e83d8663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
